name: CI

on:
  push:
    branches:
      - master
      - workflows
    tags:
      - '*'
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet: [ 6.0.x ]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci:skip')"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore Tool
      run: dotnet tool restore

    - name: Format.Check
      run: dotnet fake build -t format.check

    - name: Build
      run: dotnet fake build

    - name: Build(Release)
      run: dotnet fake build -- RELEASE

    - name: Test
      run: dotnet fake build -t test

    - name: NuGet
      if: startsWith( github.ref, 'refs/tags/')
      run: |
        dotnet pack -c Release
        cp src/AwaitableCoroutine/bin/Release/netstandard2.1/AwaitableCoroutine.dll output
        cp src/AwaitableCoroutine.Altseed2/bin/Release/netstandard2.1/AwaitableCoroutine.Altseed2.dll output
        cp src/AwaitableCoroutine.FSharp/bin/Release/netstandard2.1/AwaitableCoroutine.FSharp.dll output

    - name: Upload artifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v1.0.0
      with:
        name: output
        path: output
